version: '3.2'

services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "example"
      MYSQL_DATABASE: "tradeshift"
    networks:
      - mysql

  app:
    build: .
    ports:
      - 9090:9090
    depends_on:
      - db
    networks:
      - mysql
    restart: on-failure
networks:
  mysql:
    driver: bridge





