app:
  name: company-structure-coding-challenge

server:
  address: 0.0.0.0
  port: 9090
spring:
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  jpa:
      hibernate:
       ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
  datasource:
        url: jdbc:mysql://localhost:3306/asghar
        username: root
        password: example



