server:
  address: 0.0.0.0
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/tradeshift
    username: root
    password: example
  jpa:
    hibernate:
     ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://mysql/tradeshift
    username: root
    password: example





